### ISSUE TITLE
1.29.8 Workflow Stuck at Parameter Prompt After Submitting Parameter Values

### ISSUE THREAD

**Issue by codecrafter97** [AutomaApp/automa#1946]
**Describe the bug**
After users input parameter values and click the "Submit" button, the workflow fails to progress to the next block.

**To Reproduce**
1. Trigger workflow https://www.automa.site/workflow/fsjfz_HmxyOJBnCkvrxb5
2. Enter parameter input
3. Click submit button
4. Not responding, does not proceed to next block

**Expected behavior**
Proceed to next block

**Screenshots**
From log, it is stuck at Parameter prompt
![Image](https://github.com/user-attachments/assets/cebde02f-57fe-4604-bcf9-18b32e0b1d79)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge
 - Extension Version: 1.29.8

**Additional context**
This issue began occurring today, and the workflow was functioning correctly yesterday.

**Comment by bingren-yd** [comment]
Are there any specific value requirements for the parameters to be filled in?

After attempting to install and run the program, I entered "1" and was redirected to https://page-blank.vercel.app/.

It appears to be functioning as expected.

**Comment by codecrafter97** [comment]
Attached is the recording.

I have reinstalled Automa v1.29.8.

The first workflow trigger worked correctly.

However, subsequent workflow triggers get stuck at the parameter prompt.

https://github.com/user-attachments/assets/b09e4099-c4c1-41b4-a123-1d8a75e69735

Only the first workflow able to proceed to the JavaScript code block

![Image](https://github.com/user-attachments/assets/c690baf4-c3e5-4e0c-aa3a-ddd3aa6c21b5)

**Comment by zhongqingsong** [comment]
yeah, i am the same problem.

**Comment by nbvnbv** [comment]
+1

**Comment by nightrider77** [comment]
I have the same issue on v1.29.9, parameter prompt stucks.

**Comment by 3Deyedoc** [comment]
Same issue here. 

![Image](https://github.com/user-attachments/assets/90052a06-caf1-4c1c-b298-b19b45a1228a)

**Comment by nightrider77** [comment]
@bingren-yd Mister, when is this issue expected to be resolved? Thank you.

**Comment by 3Deyedoc** [comment]
@bingren-yd I'm curious too. I can't find a good work around. The parameter prompt will work on occasion. When it does it's only the first prompt the first time after rebooting my computer.

**Comment by yourlocalmudpuppy** [comment]
Same issue here, however it seems to only happen on Chromium based browsers (tested Chrome, Edge, Vivaldi, Opera). Anything Firefox based works fine (tested Firefox, Zen, LibreWolf, Waterfox, Floorp).

**Comment by 3Deyedoc** [comment]
I saw the update but still getting the same issue. It will work the first time but everytime after the parameter prompt doesn't move forward. 


![Image](https://github.com/user-attachments/assets/ae7eb175-c929-46bb-9bbd-8d37fbcfcafd)

**Comment by deveshruttala-edu** [comment]
👋 Hey there! This looks like something Hyperbrowser could assist with. We're building an AI-native browser that automates workflows, integrates smart tools, and enhances productivity directly inside the browser. If you're tackling tasks like this often, Hyperbrowser might be just what you need.

🚀 Learn more and try it out: https://www.hyperbrowser.ai/
We’d love your feedback!

**Comment by SimFG** [comment]
I also encountered, version: 1.29.10

**Comment by SimFG** [comment]
In addition, it seems that it is impossible to get the parameters in the prompt, such as {{ variables.keyword }}

**Comment by SimFG** [comment]
https://github.com/SimFG/automa/commit/24172254ad1bd6d0bdad7b7770a62028fcb56079
I tried to fix it with cursor, but I am not familiar with the front end. I have tried the case I used and the problem should have been solved.

**Comment by qq-admin** [comment]
I have the same issue on v1.29.10, parameter prompt stucks.

**Comment by expanous** [comment]
Same problem - works only once and then stops working. Variables are empty after 1st run.

**Comment by iMoeenD** [comment]
The parameter block is a crucial feature in browser automation tools, particularly in Automa. Unfortunately, I've discovered that it only functions correctly when included in trigger blocks. If you add the parameters block anywhere else within the workflow, it fails to work properly. Despite multiple updates since this issue was first noticed, the problem persists. We hope the @bingren-yd can address and resolve this technical limitation soon.

**Comment by 3Deyedoc** [comment]
Still waiting on a solution for this bug. I hope there's been progress.

**Comment by 3Deyedoc** [comment]
Can we at least get a comment on fixing this feature we are on 1.29.12 and the parameter prompt still does not work. I have work flows that use this feature and have been waiting for a fix.  @bingren-yd  If you aren't going to fix it then remove the feature because it does not function properly. After a reboot it will work once and then stop working every time after that.

**Comment by chenhz01** [comment]
The recording in the report shows the workflow wedged at the parameter prompt after submit — the transition following a human input gate never fires, and nothing records that the gate completed. SimFG has also posted a community-side fix attempt on a fork; a durable executor-level guarantee is still missing. My approach: model the parameter prompt as an explicit human gate. On submit, the executor writes gate_completed with the values into the run state, then resumes from the next block via a deterministic continuation pointer; if no acknowledgment arrives within a timeout, it fails loudly instead of waiting forever. That guarantees the pause-resume seam can't silently drop progress.

state.gates[param_prompt] = done; resume_from(next_block_id)

Want me to take a crack at it? Happy to open a PR with working code.
